
import { v4 as uuidv4 } from 'uuid'
import type {
  Customer,
  Vehicle,
  RepairOrder,
} from '../types'
import { OrderStatus, OrderSource, EventType, BusinessErrorType } from '../types'

const CUSTOMER_IDS = {
  CUSTOMER_1: '1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d',
  CUSTOMER_2: '2b3c4d5e-6f7a-4b8c-9d0e-1f2a3b4c5d6e',
  CUSTOMER_3: '3c4d5e6f-7a8b-4c9d-0e1f-2a3b4c5d6e7f',
  CUSTOMER_4: '4d5e6f7a-8b9c-4d0e-1f2a-3b4c5d6e7f8a',
}

const VEHICLE_IDS = {
  VEHICLE_1: '5e6f7a8b-9c0d-4e1f-2a3b-4c5d6e7f8a9b',
  VEHICLE_2: '6f7a8b9c-0d1e-4f2a-3b4c-5d6e7f8a9b0c',
  VEHICLE_3: '7a8b9c0d-1e2f-4a3b-4c5d-6e7f8a9b0c1d',
  VEHICLE_4: '8b9c0d1e-2f3a-4b4c-5d6e-7f8a9b0c1d2e',
  VEHICLE_5: '9c0d1e2f-3a4b-4c5d-6e7f-8a9b0c1d2e3f',
}

export const mockCustomers: Customer[] = [
  {
    id: CUSTOMER_IDS.CUSTOMER_1,
    name: 'Juan Pérez García',
    phone: '55-1234-5678',
    email: 'juan.perez@email.com',
  },
  {
    id: CUSTOMER_IDS.CUSTOMER_2,
    name: 'María González López',
    phone: '55-8765-4321',
    email: 'maria.gonzalez@email.com',
  },
  {
    id: CUSTOMER_IDS.CUSTOMER_3,
    name: 'Carlos Rodríguez Martínez',
    phone: '55-5555-6666',
    email: 'carlos.rodriguez@email.com',
  },
  {
    id: CUSTOMER_IDS.CUSTOMER_4,
    name: 'Ana Martínez Sánchez',
    phone: '55-9999-0000',
  },
]

export const mockVehicles: Vehicle[] = [
  {
    id: VEHICLE_IDS.VEHICLE_1,
    plate: 'ABC-123-D',
    model: 'Toyota Corolla 2020',
    customerId: CUSTOMER_IDS.CUSTOMER_1,
  },
  {
    id: VEHICLE_IDS.VEHICLE_2,
    plate: 'XYZ-789-F',
    model: 'Honda Civic 2019',
    customerId: CUSTOMER_IDS.CUSTOMER_2,
  },
  {
    id: VEHICLE_IDS.VEHICLE_3,
    plate: 'DEF-456-G',
    model: 'Nissan Versa 2021',
    customerId: CUSTOMER_IDS.CUSTOMER_3,
  },
  {
    id: VEHICLE_IDS.VEHICLE_4,
    plate: 'GHI-111-H',
    model: 'Mazda 3 2018',
    customerId: CUSTOMER_IDS.CUSTOMER_4,
  },
  {
    id: VEHICLE_IDS.VEHICLE_5,
    plate: 'JKL-222-I',
    model: 'Ford Focus 2017',
    customerId: CUSTOMER_IDS.CUSTOMER_1,
  },
]

const ORDER_IDS = {
  ORDER_1: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
  ORDER_2: 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e',
  ORDER_3: 'c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f',
  ORDER_4: 'd4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a',
  ORDER_5: 'e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b',
  ORDER_6: 'f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c',
}

export const mockOrders: RepairOrder[] = [
  // Orden 1: CREATED - Recién creada desde el taller
  {
    id: ORDER_IDS.ORDER_1,
    orderId: 'RO-001',
    customerId: CUSTOMER_IDS.CUSTOMER_1,
    vehicleId: VEHICLE_IDS.VEHICLE_1,
    status: OrderStatus.CREATED,
    subtotalEstimated: 0,
    authorizedAmount: 0,
    realTotal: 0,
    authorizations: [],
    services: [],
    events: [
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_1,
        type: EventType.ORDEN_CREADA,
        toStatus: OrderStatus.CREATED,
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
    ],
    errors: [],
    source: OrderSource.TALLER,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  // Orden 2: DIAGNOSED - Con servicios, pendiente de autorización
  {
    id: ORDER_IDS.ORDER_2,
    orderId: 'RO-002',
    customerId: CUSTOMER_IDS.CUSTOMER_2,
    vehicleId: VEHICLE_IDS.VEHICLE_2,
    status: OrderStatus.DIAGNOSED,
    subtotalEstimated: 1750,
    authorizedAmount: 0,
    realTotal: 1750,
    authorizations: [],
    services: [
      {
        id: 'svc-001',
        orderId: ORDER_IDS.ORDER_2,
        name: 'Cambio de aceite y filtro',
        description: 'Servicio de mantenimiento regular',
        laborEstimated: 300,
        laborReal: 300,
        components: [
          {
            id: uuidv4(),
            serviceId: 'svc-001',
            name: 'Filtro de aceite',
            description: 'Filtro original',
            estimated: 150,
            real: 150,
          },
          {
            id: uuidv4(),
            serviceId: 'svc-001',
            name: 'Aceite sintético 5W-30',
            description: '4 litros',
            estimated: 800,
            real: 800,
          },
        ],
      },
      {
        id: 'svc-002',
        orderId: ORDER_IDS.ORDER_2,
        name: 'Revisión de frenos',
        description: 'Inspección y ajuste',
        laborEstimated: 500,
        laborReal: 500,
        components: [],
      },
    ],
    events: [
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_2,
        type: EventType.ORDEN_CREADA,
        toStatus: OrderStatus.CREATED,
        timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_2,
        type: EventType.ORDEN_DIAGNOSTICADA,
        fromStatus: OrderStatus.CREATED,
        toStatus: OrderStatus.DIAGNOSED,
        timestamp: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
      },
    ],
    errors: [],
    source: OrderSource.CLIENTE,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },
  // Orden 3: AUTHORIZED - Autorizada por el cliente, lista para iniciar
  {
    id: ORDER_IDS.ORDER_3,
    orderId: 'RO-003',
    customerId: CUSTOMER_IDS.CUSTOMER_3,
    vehicleId: VEHICLE_IDS.VEHICLE_3,
    status: OrderStatus.AUTHORIZED,
    subtotalEstimated: 2450,
    authorizedAmount: 2450.0,
    realTotal: 2450,
    authorizations: [
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_3,
        amount: 2450.0,
        createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        comment: 'Autorización inicial',
      },
    ],
    services: [
      {
        id: 'svc-003',
        orderId: ORDER_IDS.ORDER_3,
        name: 'Cambio de balatas',
        description: 'Balatas delanteras desgastadas',
        laborEstimated: 1000,
        laborReal: 1000,
        components: [
          {
            id: uuidv4(),
            serviceId: 'svc-003',
            name: 'Balatas delanteras',
            description: 'Juego completo',
            estimated: 1200,
            real: 1200,
          },
          {
            id: uuidv4(),
            serviceId: 'svc-003',
            name: 'Líquido de frenos',
            description: 'DOT 4',
            estimated: 250,
            real: 250,
          },
        ],
      },
    ],
    events: [
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_3,
        type: EventType.ORDEN_CREADA,
        toStatus: OrderStatus.CREATED,
        timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_3,
        type: EventType.ORDEN_DIAGNOSTICADA,
        fromStatus: OrderStatus.CREATED,
        toStatus: OrderStatus.DIAGNOSED,
        timestamp: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_3,
        type: EventType.ORDEN_AUTORIZADA,
        fromStatus: OrderStatus.DIAGNOSED,
        toStatus: OrderStatus.AUTHORIZED,
        timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      },
    ],
    errors: [],
    source: OrderSource.TALLER,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  // Orden 4: IN_PROGRESS - En reparación
  {
    id: ORDER_IDS.ORDER_4,
    orderId: 'RO-004',
    customerId: CUSTOMER_IDS.CUSTOMER_4,
    vehicleId: VEHICLE_IDS.VEHICLE_4,
    status: OrderStatus.IN_PROGRESS,
    subtotalEstimated: 2050,
    authorizedAmount: 2050.0,
    realTotal: 2050,
    authorizations: [
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_4,
        amount: 2050.0,
        createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        comment: 'Autorización inicial',
      },
    ],
    services: [
      {
        id: 'svc-004',
        orderId: ORDER_IDS.ORDER_4,
        name: 'Cambio de aceite',
        description: 'Servicio completo',
        laborEstimated: 300,
        laborReal: 300,
        components: [
          {
            id: uuidv4(),
            serviceId: 'svc-004',
            name: 'Filtro de aceite',
            description: 'Filtro original',
            estimated: 150,
            real: 150,
          },
          {
            id: uuidv4(),
            serviceId: 'svc-004',
            name: 'Aceite sintético 5W-30',
            description: '4 litros',
            estimated: 800,
            real: 800,
          },
        ],
      },
      {
        id: 'svc-005',
        orderId: ORDER_IDS.ORDER_4,
        name: 'Alineación y balanceo',
        description: 'Ajuste de suspensión',
        laborEstimated: 800,
        laborReal: 800,
        components: [],
      },
    ],
    events: [
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_4,
        type: EventType.ORDEN_CREADA,
        toStatus: OrderStatus.CREATED,
        timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_4,
        type: EventType.ORDEN_DIAGNOSTICADA,
        fromStatus: OrderStatus.CREATED,
        toStatus: OrderStatus.DIAGNOSED,
        timestamp: new Date(Date.now() - 60 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_4,
        type: EventType.ORDEN_AUTORIZADA,
        fromStatus: OrderStatus.DIAGNOSED,
        toStatus: OrderStatus.AUTHORIZED,
        timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_4,
        type: EventType.ORDEN_INICIADA,
        fromStatus: OrderStatus.AUTHORIZED,
        toStatus: OrderStatus.IN_PROGRESS,
        timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      },
    ],
    errors: [],
    source: OrderSource.TALLER,
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  // Orden 5: WAITING_FOR_APPROVAL - Excedió el límite del 110%
  {
    id: ORDER_IDS.ORDER_5,
    orderId: 'RO-005',
    customerId: CUSTOMER_IDS.CUSTOMER_1,
    vehicleId: VEHICLE_IDS.VEHICLE_5,
    status: OrderStatus.WAITING_FOR_APPROVAL,
    subtotalEstimated: 5100,
    authorizedAmount: 5100.0,
    realTotal: 5950,
    authorizations: [
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_5,
        amount: 5100.0,
        createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        comment: 'Autorización inicial',
      },
    ],
    services: [
      {
        id: 'svc-006',
        orderId: ORDER_IDS.ORDER_5,
        name: 'Cambio de amortiguadores',
        description: 'Amortiguadores delanteros',
        laborEstimated: 2000,
        laborReal: 2500,
        components: [
          {
            id: uuidv4(),
            serviceId: 'svc-006',
            name: 'Amortiguador delantero izquierdo',
            description: 'Original',
            estimated: 2500,
            real: 2800,
          },
          {
            id: uuidv4(),
            serviceId: 'svc-006',
            name: 'Goma de suspensión',
            description: 'Kit completo',
            estimated: 600,
            real: 650,
          },
        ],
      },
    ],
    events: [
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_5,
        type: EventType.ORDEN_CREADA,
        toStatus: OrderStatus.CREATED,
        timestamp: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_5,
        type: EventType.ORDEN_DIAGNOSTICADA,
        fromStatus: OrderStatus.CREATED,
        toStatus: OrderStatus.DIAGNOSED,
        timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_5,
        type: EventType.ORDEN_AUTORIZADA,
        fromStatus: OrderStatus.DIAGNOSED,
        toStatus: OrderStatus.AUTHORIZED,
        timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_5,
        type: EventType.ORDEN_INICIADA,
        fromStatus: OrderStatus.AUTHORIZED,
        toStatus: OrderStatus.IN_PROGRESS,
        timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_5,
        type: EventType.ORDEN_REAUTORIZADA,
        fromStatus: OrderStatus.IN_PROGRESS,
        toStatus: OrderStatus.WAITING_FOR_APPROVAL,
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        comment: 'Requiere reautorización por sobrecosto',
      },
    ],
    errors: [
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_5,
        type: BusinessErrorType.REQUIRES_REAUTH,
        message: 'El costo real ($5950.00) excede el límite autorizado ($5610.00)',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
    ],
    source: OrderSource.TALLER,
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  // Orden 6: COMPLETED - Terminada, pendiente de entrega
  {
    id: ORDER_IDS.ORDER_6,
    orderId: 'RO-006',
    customerId: CUSTOMER_IDS.CUSTOMER_2,
    vehicleId: VEHICLE_IDS.VEHICLE_2,
    status: OrderStatus.COMPLETED,
    subtotalEstimated: 2450,
    authorizedAmount: 2450.0,
    realTotal: 2450,
    authorizations: [
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_6,
        amount: 2450.0,
        createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
        comment: 'Autorización inicial',
      },
    ],
    services: [
      {
        id: 'svc-007',
        orderId: ORDER_IDS.ORDER_6,
        name: 'Servicio mayor',
        description: 'Revisión completa a 80,000 km',
        laborEstimated: 1500,
        laborReal: 1500,
        components: [
          {
            id: uuidv4(),
            serviceId: 'svc-007',
            name: 'Filtro de aceite',
            description: 'Filtro original',
            estimated: 150,
            real: 150,
          },
          {
            id: uuidv4(),
            serviceId: 'svc-007',
            name: 'Aceite sintético 5W-30',
            description: '4 litros',
            estimated: 800,
            real: 800,
          },
        ],
      },
    ],
    events: [
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_6,
        type: EventType.ORDEN_CREADA,
        toStatus: OrderStatus.CREATED,
        timestamp: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_6,
        type: EventType.ORDEN_DIAGNOSTICADA,
        fromStatus: OrderStatus.CREATED,
        toStatus: OrderStatus.DIAGNOSED,
        timestamp: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_6,
        type: EventType.ORDEN_AUTORIZADA,
        fromStatus: OrderStatus.DIAGNOSED,
        toStatus: OrderStatus.AUTHORIZED,
        timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_6,
        type: EventType.ORDEN_INICIADA,
        fromStatus: OrderStatus.AUTHORIZED,
        toStatus: OrderStatus.IN_PROGRESS,
        timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: uuidv4(),
        orderId: ORDER_IDS.ORDER_6,
        type: EventType.ORDEN_COMPLETADA,
        fromStatus: OrderStatus.IN_PROGRESS,
        toStatus: OrderStatus.COMPLETED,
        timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      },
    ],
    errors: [],
    source: OrderSource.CLIENTE,
    createdAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
]
